
const keywords: string[] = [
    "nutrition", 
    "diet",
    "meal plan",
    "healthy eating",
    "meal prep",
    "calories",
    "macros",
    "macronutrients",
    "protein",
    "carbohydrates",
    "fats",
    "vitamins",
    "minerals",
    "supplements",
    "hydration",
    "water intake",
    "portion control",
    "food groups",
    "nutrient dense",
    "superfoods",
    "whole foods",
    "processed foods",
    "organic",
    "gmo",
    "gluten",
    "lactose",
    "dairy",
    "vegan",
    "vegetarian",
    "plant-based",
    "paleo",
    "keto",
    "intermittent fasting",
    "metabolism",
    "digestion",
    "gut health",
    "probiotics",
    "antioxidants",
    "inflammation",

    "weight loss",
    "weight gain",
    "body composition",
    "bulking",
    "cutting",
    "maintenance",
    "body fat percentage",
    "lean mass",
    "muscle mass",
    "body mass index",
    "bmi",
    "caloric deficit",
    "caloric surplus",
    "maintenance calories",
    "tdee",
    "basal metabolic rate",
    "bmr",
    
    "workout",
    "exercise",
    "fitness",
    "training program",
    "fitness goals",
    "personal trainer",
    "exercise routine",
    "strength training",
    "resistance training",
    "cardio",
    "cardiovascular",
    "aerobic",
    "anaerobic",
    "flexibility",
    "mobility",
    "endurance",
    "hiit",
    "high intensity interval training",
    "crossfit",
    "bodyweight exercises",
    "weightlifting",
    "powerlifting",
    "calisthenics",
    "yoga",
    "pilates",
    "stretching",
    "warm up",
    "cool down",
    "recovery",
    "rest day",
    "overtraining",
    "progressive overload",
    "reps",
    "sets",
    "form",
    "technique",

    "wellness",
    "health tips",
    "lifestyle",
    "sleep",
    "stress management",
    "mental health",
    "hormones",
    "immune system",
    "energy levels",
    "fatigue",
    "performance",
    "athletic performance",
    "endurance",
    "stamina",

    "mediterranean diet",
    "dash diet",
    "low carb",
    "high protein",
    "carnivore",
    "whole30",
    "atkins",
    "zone diet",
    "alkaline diet",
    "blood type diet",
    "south beach diet",
    "weight watchers",
    "noom",
    "calorie counting",
    "macro counting",
    "iifym",
    "if it fits your macros",
    "meal frequency",
    "intuitive eating",
    "mindful eating",
    
    "scale",
    "weight",
    "measurements",
    "progress photos",
    "tracking",
    "fitness tracker",
    "smart watch",
    "heart rate",
    "steps",
    "activity level",

    "food allergies",
    "food sensitivities",
    "food intolerances",
    "celiac",
    "diabetes",
    "insulin resistance",
    "cholesterol",
    "blood pressure",
    "heart health",
    "digestive issues",
    "ibs",
    
    "protein powder",
    "creatine",
    "pre-workout",
    "bcaa",
    "amino acids",
    "omega-3",
    "fish oil",
    "multivitamin",
    "vitamin d",
    "iron",
    "calcium",
    "magnesium",
    "zinc",
    "electrolytes"
  ];
export const isRelevant = (message: string): boolean => {
    const lowerCaseMessage = message.toLowerCase();
    return keywords.some((keyword) => lowerCaseMessage.includes(keyword));
}